 # Inkluder exception melding i svar.
spring:
  web:
    resources:
      add-mappings: false
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

# This property is deprecated: DispatcherServlet property is deprecated for removal and should no longer need to be configured
# throw-exception-if-no-handler-found: true

springfox:
  documentation:
    swagger-ui:
      base-url: "/docs"

saf:
  url: "${SAF_GRAPHQL}"
  scope: "${SAF_GRAPHQL_SCOPE}"

dokarkiv:
  url: "${DOKARKIV_BASE_URL}"
  scope: "${DOKARKIV_SCOPE}"

distribuer-journalpost:
  url: "${DISTRIBUER_JOURNALPOST_URL}"
  scope: "${DISTRIBUER_JOURNALPOST_SCOPE}"

brevmetadata:
  url: "${BREVMETADATA_URL}"
spring.web.error.include-message: always