# Inkluder exception melding i svar.
spring:
  web:
    resources:
      add-mappings: false
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
# This property is deprecated: DispatcherServlet property is deprecated for removal and should no longer need to be configured
# throw-exception-if-no-handler-found: true

springfox:
  documentation:
    swagger-ui:
      base-url: "/docs"

saf:
  url: "${SAF_GRAPHQL}"
  scope: "${SAF_GRAPHQL_SCOPE}"

dokarkiv:
  url: "${DOKARKIV_BASE_URL}"
  scope: "${DOKARKIV_SCOPE}"

distribuer-journalpost:
  url: "${DISTRIBUER_JOURNALPOST_URL}"
  scope: "${DISTRIBUER_JOURNALPOST_SCOPE}"

brevmetadata:
  url: "${BREVMETADATA_URL}"
spring.web.error.include-message: always


# Configuration values different environments
#
#
# SAF
#   FSS:
#     prod: https://saf.intern.nav.no
#     dev:  https://saf.dev.intern.nav.no
#   GCP:
#     prod: https://saf.prod-fss-pub.nais.io
#     dev:  https://saf.dev-fss-pub.nais.io
#   Scopes:
#     prod: api://prod-fss.teamdokumenthandtering.saf/.default
#     dev:  api://dev-fss.teamdokumenthandtering.saf/.default
#
# Dokarkiv
#   FSS:
#     prod: https://dokarkiv.intern.nav.no
#     dev:	https://dokarkiv.dev.intern.nav.no
#   GCP:
#     prod: https://dokarkiv.prod-fss-pub.nais.io
#     dev:  https://dokarkiv-q2.dev-fss-pub.nais.io
#   Scopes:
#     prod: api://prod-fss.teamdokumenthandtering.dokarkiv/.default
#     dev: 	api://dev-fss.teamdokumenthandtering.dokarkiv/.default
#
# dokdistfordeling
#   FSS
#     prod: https://dokdistfordeling.intern.nav.no
#     dev:  https://dokdistfordeling.dev.intern.nav.no
#   GCP
#     prod: https://dokdistfordeling.prod-fss-pub.nais.io
#     dev:  https://dokdistfordeling.dev-fss-pub.nais.io
#   Scopes:
#     prod: api://prod-fss.teamdokumenthandtering.dokdistfordeling/.default
#     dev:  api://dev-fss.teamdokumenthandtering.dokdistfordeling/.default
